# Generated by Django 3.1.7 on 2021-03-31 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название работ')),
                ('fix_percent', models.IntegerField(null=True, verbose_name='Процент от услуги')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('sum_for_worker', models.IntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.CharField(max_length=150, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.typeofwork', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оказаная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
        ),
    ]
