# Generated by Django 3.1.7 on 2021-03-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairCut',
            fields=[
                ('typeofwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counter.typeofwork')),
                ('persent_from_price', models.IntegerField()),
            ],
            bases=('counter.typeofwork',),
        ),
        migrations.AlterModelOptions(
            name='typeofwork',
            options={'verbose_name': 'Вид работ', 'verbose_name_plural': 'Вид работ'},
        ),
        migrations.RemoveField(
            model_name='typeofwork',
            name='percent_from_price',
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
