# Generated by Django 3.1.7 on 2021-03-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20210317_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofwork',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='sum_for_worker',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма чистыми'),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название работ'),
        ),
    ]
