# Generated by Django 3.1.7 on 2021-03-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20210318_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HairCut',
        ),
    ]
