# Generated by Django 3.1.7 on 2021-03-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_delete_haircut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofwork',
            name='price',
        ),
        migrations.RemoveField(
            model_name='typeofwork',
            name='sum_for_worker',
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='fix_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AddService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('sum_for_worker', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.typeofwork')),
            ],
        ),
    ]
