# Generated by Django 3.1.7 on 2021-03-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20210318_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addservice',
            options={'verbose_name': 'Оказаная услуга', 'verbose_name_plural': 'Оказанные услуги'},
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='fix_percent',
            field=models.IntegerField(null=True, verbose_name='Процент от услуги'),
        ),
    ]
