# Generated by Django 3.1.7 on 2021-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20210318_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservice',
            name='sum_for_worker',
            field=models.IntegerField(blank=True),
        ),
    ]
