# Generated by Django 3.1.7 on 2021-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0009_auto_20210319_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='date_add',
            field=models.DateTimeField(null=True),
        ),
    ]
