# Generated by Django 3.1.7 on 2021-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0010_addservice_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservice',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
