# Generated by Django 3.1.7 on 2021-03-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_auto_20210327_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='user',
        ),
        migrations.RemoveField(
            model_name='typeofwork',
            name='user',
        ),
    ]
