# Generated by Django 3.1.7 on 2021-03-27 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0015_auto_20210327_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesList',
            new_name='Services',
        ),
    ]
