# Generated by Django 3.1.7 on 2021-03-29 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0018_auto_20210328_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofwork',
            name='user',
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
